homepage:
    pattern:  /
    defaults: { _controller: SensioHangmanBundle:Game:index }

sensio_hangman:
    resource:  "@SensioHangmanBundle/Controller"

login_check:
    path: /auth
    requirements: { _method: POST }

signout:
    path: /logout
