jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        # Symfony\Component\Security\Core\User\User: plaintext
        Sensio\Bundle\HangmanBundle\Entity\Player: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        players: 
            entity: { class: SensioHangmanBundle:Player, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        game:
            pattern:  ^/
            anonymous: true
            form_login:
                login_path:     signin
                check_path:     login_check
                default_target_path:    hangman_game
                always_use_default_target_path: true
            logout:
                path: signout
                target: signin 

    access_control:
        - { path: ^/game, roles: IS_AUTHENTICATED_FULLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
