<?php

namespace Sensio\Bundle\HangmanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    public function findRecentPlayers($max)
    {
        $q = $this
             ->createQueryBuilder('p')
->select('p.id, p.username')
->where('p.isActive = :active')
->andWhere('p.isAdmin = :admin')
->orderBy('p.id', 'DESC')
->setMaxResults($max)
->setParameter('active', true)
->setParameter('admin', false)
->getQuery()
;
    
    return $q->getArrayResult();

    }
}
